version: "3.9"

services:
  spring-app:
    image: toonpick-service-app:0.0.1
    container_name: toonpick-service-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    
    environment:
      LOG_FILE: /app/logs/application.log
    
    restart: always

