name: TOONPICK Backend CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle 캐시 설정 (빌드 최적화)
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Gradle 실행 권한 추가
        run: chmod +x backend/gradlew

      - name: Gradle 빌드 및 테스트
        working-directory: backend
        run: |
          ./gradlew clean build -x test --no-daemon --parallel --configure-on-demand

      - name: 빌드 결과 검증 (JAR 파일 확인)
        run: |
          echo "=== Gradle Build 완료 후 JAR 파일 위치 확인 ==="
          find backend/build/libs -type f -name "*.jar"
          ls -al backend/build/libs

      - name: 빌드된 JAR 파일 업로드 (아티팩트 저장)
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/build/libs/toonpick-0.0.1-SNAPSHOT.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 빌드된 JAR 파일 다운로드 (아티팩트 복원)
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: backend/build/libs

      - name: JAR 파일 위치 확인
        run: |
          echo "=== JAR 파일 위치 ==="
          find backend -name "*.jar"
        
      - name: Docker Build & Push
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          REPOSITORY: "toonpick-service-app"
          IMAGE_TAG: "v0.1.${{ github.run_number }}"
        run: |
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          
          echo "=== Docker Build 시작 ==="
          echo "현재 작업 디렉토리:"
          pwd
          
          echo "=== 현재 디렉토리 내 파일 목록 ==="
          ls -al backend

          echo "=== 현재 디렉토리 내 파일 목록 ==="
          ls -al backend/build/libs

          echo "=== JAR 파일이 존재하는지 확인 ==="
          ls -al backend || echo "JAR 파일이 존재하지 않습니다."

          echo "=== Docker Build 수행 ==="
          docker build -t $DOCKER_HUB_USERNAME/$REPOSITORY:$IMAGE_TAG -f backend/Dockerfile .
          docker build -t $DOCKER_HUB_USERNAME/$REPOSITORY:latest -f backend/Dockerfile .
          
          docker push $DOCKER_HUB_USERNAME/$REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_HUB_USERNAME/$REPOSITORY:latest
