name: TOONPICK Backend CD Pipeline

on:
  workflow_run:
    workflows: ["TOONPICK Backend CI Pipeline"]
    types:
      - completed

permissions:
  actions: write
  contents: write

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 SSH 접속하여 배포 실행
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/TOONPICK

            echo "최신 Docker Image Pull & 배포 시작..."

            docker stop toonpick-service-app || true
            docker rm toonpick-service-app || true
            
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/toonpick-service-app:latest
            
            docker-compose up -d
